### ISSUE TITLE
Examples LCD gives an error

### ISSUE THREAD

**Issue by JBSchueler** [pimoroni/enviroplus-python#34]
While following the [getting started guide](https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-enviro-plus) but ran into problems while testing the LCD.
I get this error

```
pi@raspberrypi:~/enviroplus-python/examples $ python lcd.py
Traceback (most recent call last):
  File "lcd.py", line 3, in <module>
    import ST7735
  File "/usr/local/lib/python2.7/dist-packages/ST7735-0.0.3-py2.7.egg/ST7735/__init__.py", line 25, in <module>
    import spidev
ImportError: No module named spidev
pi@raspberrypi:~/enviroplus-python/examples $
```

the same for `all-in-one.py`
```
pi@raspberrypi:~/enviroplus-python/examples $ python all-in-one.py
Traceback (most recent call last):
  File "all-in-one.py", line 7, in <module>
    import ST7735
  File "/usr/local/lib/python2.7/dist-packages/ST7735-0.0.3-py2.7.egg/ST7735/__init__.py", line 25, in <module>
    import spidev
ImportError: No module named spidev
pi@raspberrypi:~/enviroplus-python/examples $
```

installed python version is 2.7.16
```
pi@raspberrypi:~/enviroplus-python/examples $ python
Python 2.7.16 (default, Apr  6 2019, 01:42:57)
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
[1]+  Stopped                 python
pi@raspberrypi:~/enviroplus-python/examples $
```

What can be the problem?

**Comment by JBSchueler** [comment]
Forgot to mention I use `2019-07-10-raspbian-buster-lite`

**Comment by JBSchueler** [comment]
Installed `2019-07-10-raspbian-buster-full` and everything seems to work like a charm.

**Comment by nophead** [comment]
The fix for buster-light is ```pip install spidev```

**Comment by JBSchueler** [comment]
I tried to install spidev but pip didn't work.
after installing pip, I tried like you describe but pip was not installing anything... had to press ctrl-c after a while to get back to the terminal.

**Comment by beamzer** [comment]
It should have worked with pip. But it should have been fixed in the install.sh script also ;)

` % ./lcd.py
Traceback (most recent call last):
  File "./lcd.py", line 3, in <module>
    import ST7735
  File "/usr/local/lib/python2.7/dist-packages/ST7735-0.0.3-py2.7.egg/ST7735/__init__.py", line 25, in <module>
    import spidev
ImportError: No module named spidev

pi@raspberrypi ~/GIT/enviroplus-python/examples
 % pip install spidev
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting spidev
  Downloading https://files.pythonhosted.org/packages/fb/14/4c2e1640f0cb04862c76d9d76ed7c945b0f67876e503ac02f7f675fe86a0/spidev-3.4.tar.gz
Building wheels for collected packages: spidev
  Running setup.py bdist_wheel for spidev ... done
  Stored in directory: /home/pi/.cache/pip/wheels/10/d6/98/ba1f1999099e3e7adb3a0140af8c9287ff2b067ff005485674
Successfully built spidev
Installing collected packages: spidev
Successfully installed spidev-3.4
 
pi@raspberrypi ~/GIT/enviroplus-python/examples
 % ./lcd.py
2020-01-29 21:20:28.080 INFO     lcd.py - Hello, World! example on the 0.96" LCD.

Press Ctrl+C to exit!`
